/**
 * wsGestplusAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.microplus.wsGestplus.models

/**
 * 
 * @param idDoc 
 * @param isoriginal 
 * @param descontoGarantia 
 * @param descontoClienteValor 
 * @param descontoFinanceiroValor 
 * @param descontoCliente 
 * @param descontoFinanceiro 
 * @param mbWayNumero 
 * @param mbWayToken 
 * @param mbWayTokenDone 
 * @param origemID 
 * @param erro 
 * @param docID 
 * @param docIDOrigem 
 * @param docIDHistorico 
 * @param armazemNome 
 * @param estado 
 * @param textoEmail 
 * @param isManual 
 * @param isImportDoc 
 * @param exportadoSAFT 
 * @param exportadoData 
 * @param objDadosHash 
 * @param anulado 
 * @param anuladoData 
 * @param localDescarga 
 * @param localCarga 
 * @param objlinhas 
 * @param objTotais 
 * @param objTotaisConverted 
 * @param objTaxas 
 * @param objCliente 
 * @param isDocumentoSAFT 
 * @param isDocumentTransporte 
 * @param objTipoDocumento 
 * @param dataPedido 
 * @param dataConclusao 
 * @param ticketN 
 * @param idTicketPrioridade 
 * @param servicoPeriodicidade 
 * @param servicoDataProximoAlerta 
 * @param servicoDescricao 
 * @param servicoId 
 * @param gestplusIDCliente 
 * @param gestplusPeriodicidade 
 * @param gestplusDataProximoAlerta 
 * @param avencaNPrestacoes 
 * @param avencaNPrestacoesDone 
 * @param avencaNPrestacoesPaid 
 * @param docNome 
 * @param idLogin 
 * @param documentoNumero 
 * @param documentoTipo 
 * @param documentoLoja 
 * @param documentoSerie 
 * @param documentoPrograma 
 * @param idSerie 
 * @param serie 
 * @param nif 
 * @param iDMesa 
 * @param pago 
 * @param pagoTot 
 * @param docCli 
 * @param &#x60;data&#x60; 
 * @param dataInicio 
 * @param dataFim 
 * @param prioricidade 
 * @param dataPagamento 
 * @param vEncomendaOnline 
 * @param vReferencia 
 * @param numeroEnc 
 * @param objTipoPagamentoDocumento 
 * @param aPartirDeSubscricao 
 * @param facturaAssociadaAGt 
 * @param confirmarTipoPagamento 
 * @param talaoRecibo 
 * @param vendaDirecta 
 * @param pos 
 * @param moeda 
 * @param obs 
 * @param pendenteRevendedor 
 * @param eLicElectronica 
 * @param iDClienteRetalhista 
 * @param iDLicTemp 
 * @param dataAprovacaoLicEletronica 
 * @param rascunhoTDoc 
 * @param rascunhodocid 
 * @param versionCert 
 * @param titulo 
 * @param idTecnico 
 * @param idEstadoTecnico 
 * @param docForn 
 * @param idBancoConta 
 * @param clienteNome 
 * @param clienteMorada 
 * @param clienteCidade 
 * @param clienteCodPost 
 * @param clientePais 
 * @param clientePaisID 
 * @param nCartao 
 * @param geraMB 
 * @param motAnulado 
 * @param entidade 
 * @param referencia 
 * @param vencimentoObs 
 * @param troco 
 * @param cdgoPedNumero 
 * @param nomeComercial 
 * @param idTransportadora 
 * @param nTransporte 
 * @param irSTexto 
 * @param valorPago 
 * @param valorSaldado 
 * @param tipoDescontoRecibo 
 * @param descontoRecibo 
 * @param valorAposDescontoRec 
 * @param invoiceStatus 
 * @param estadoDoc 
 * @param dataEntrega 
 * @param estadoData 
 * @param numeradorOffline 
 * @param iDLojaEntrega 
 * @param sourceBilling 
 * @param idContacto 
 * @param idClienteFAC 
 * @param confirmacaoPagamento 
 * @param userConfirmacaoPagamento 
 * @param referenciaValorPago 
 * @param referenteDocumentosNumero 
 * @param referenteDocumentosTipo 
 * @param referenteDocumentosPrograma 
 * @param referenteDocumentosLoja 
 * @param atDocCodeID 
 * @param returnCode 
 * @param returnMessage 
 * @param atDocCodeIDA 
 * @param returnCodeA 
 * @param returnMessageA 
 * @param isFilial 
 * @param clienteNome 
 * @param clienteMorada 
 * @param clienteCodigoPostal 
 * @param clienteLocalidade 
 * @param clientePais 
 * @param objRevendedor 
 * @param objGestor 
 * @param objVendedor 
 * @param objVendedor 
 * @param postPoneQuerys 
 * @param prePoneQuerys 
 * @param metodoEntrega 
 */
data class DocumentHeader (
    val subscricao_origem: Int? = null,
    val id_doc: Int? = null,
    val isoriginal: Boolean? = null,
    val desconto_garantia: Double? = null,
    val desconto_Cliente_Valor: Double? = null,
    val desconto_Financeiro_valor: Double? = null,
    val desconto_Cliente: Double? = null,
    val desconto_financeiro: Double? = null,
    val mbWay_Numero: String? = null,
    val mbWay_token: String? = null,
    val mbWay_tokenDone: Int? = null,
    val origem_ID: Int? = null,
    val erro: GestError? = null,
    val docID: String? = null,
    val docIDOrigem: String? = null,
    val docIDHistorico: String? = null,
    val armazemNome: String? = null,
    val estado: Int? = null,
    val textoEmail: String? = null,
    val isManual: Boolean? = null,
    val isImportDoc: Boolean? = null,
    val exportadoSAFT: Boolean? = null,
    val exportadoData: String? = null,
    val objDadosHash: DataHash? = null,
    val anulado: Boolean? = null,
    val anuladoData: String? = null,
    val localDescarga: ShipToData? = null,
    val localCarga: ShipmentData? = null,
    val objlinhas: List<DocumentLine>? = null,
    val objTotais: TotalDocument? = null,
    val objTotaisConverted: TotalDocument? = null,
    val objTaxas: RegimeIVA? = null,
    val objCliente: EntityInfo? = null,
    val isDocumentoSAFT: Boolean? = null,
    val isDocumentTransporte: Boolean? = null,
    val objTipoDocumento: TypeDocument? = null,
    val data_pedido: String? = null,
    val data_conclusao: String? = null,
    val ticketN: String? = null,
    val idTicketPrioridade: Int? = null,
    val servico_periodicidade: Int? = null,
    val servico_data_proximo_alerta: String? = null,
    val servico_descricao: String? = null,
    val servico_id: Int? = null,
    val gestplus_ID_Cliente: Int? = null,
    val gestplus_Periodicidade: Int? = null,
    val gestplus_DataProximoAlerta: String? = null,
    val avenca_NPrestacoes: Int? = null,
    val avenca_NPrestacoes_done: Int? = null,
    val avenca_NPrestacoes_paid: Int? = null,
    val doc_nome: String? = null,
    val id_login: Int? = null,
    val documento_numero: Int? = null,
    val documento_tipo: Int? = null,
    val documento_loja: String? = null,
    val documento_Serie: String? = null,
    val documento_programa: Int? = null,
    val id_serie: String? = null,
    val serie: Series? = null,
    val nif: String? = null,
    val iD_Mesa: Int? = null,
    val pago: Boolean? = null,
    val pago_tot: Double? = null,
    val docCli: String? = null,
    val data: String? = null,
    val data_Inicio: String? = null,
    val data_Fim: String? = null,
    val prioricidade: Int? = null,
    val data_Pagamento: String? = null,
    val v_encomenda_online: String? = null,
    val v_referencia: String? = null,
    val numero_enc: Int? = null,
    val objTipoPagamentoDocumento: TypePaymentDocument? = null,
    val a_partir_de_subscricao: Int? = null,
    val factura_associada_a_gt: Int? = null,
    val confirmar_tipo_pagamento: Int? = null,
    val talao_recibo: String? = null,
    val venda_directa: Int? = null,
    val pos: Int? = null,
    val moeda: Currency? = null,
    val obs: String? = null,
    val pendente_Revendedor: Boolean? = null,
    val e_Lic_Electronica: Boolean? = null,
    val iD_Cliente_Retalhista: Int? = null,
    val iD_Lic_Temp: String? = null,
    val data_aprovacao_lic_eletronica: String? = null,
    val rascunhoTDoc: Int? = null,
    val rascunhodocid: String? = null,
    val versionCert: Int? = null,
    val titulo: String? = null,
    val idTecnico: Int? = null,
    val idEstadoTecnico: Int? = null,
    val doc_forn: String? = null,
    val id_banco_conta: Int? = null,
    val cliente_Nome: String? = null,
    val cliente_Morada: String? = null,
    val cliente_Cidade: String? = null,
    val cliente_Cod_Post: String? = null,
    val cliente_Pais: String? = null,
    val cliente_PaisID: Int? = null,
    val nCartao: String? = null,
    val geraMB: Boolean? = null,
    val mot_Anulado: String? = null,
    val entidade: String? = null,
    val referencia: String? = null,
    val vencimento_obs: String? = null,
    val troco: Double? = null,
    val cdgo_ped_numero: String? = null,
    val nomeComercial: String? = null,
    val idTransportadora: Int? = null,
    val nTransporte: String? = null,
    val irS_Texto: String? = null,
    val valor_Pago: Double? = null,
    val valor_Saldado: Double? = null,
    val tipo_Desconto_Recibo: Int? = null,
    val desconto_Recibo: Double? = null,
    val valor_Apos_Desconto_Rec: Double? = null,
    val invoiceStatus: String? = null,
    val estado_Doc: Int? = null,
    val data_Entrega: String? = null,
    val estado_Data: String? = null,
    val numerador_offline: String? = null,
    val iD_Loja_Entrega: Int? = null,
    val sourceBilling: String? = null,
    val id_contacto: Int? = null,
    val id_cliente_FAC: Int? = null,
    val confirmacao_Pagamento: Boolean? = null,
    val user_Confirmacao_Pagamento: Int? = null,
    val referencia_Valor_Pago: Double? = null,
    val referente_documentos_numero: Int? = null,
    val referente_documentos_tipo: Int? = null,
    val referente_documentos_programa: Int? = null,
    val referente_documentos_Loja: String? = null,
    val atDocCodeID: String? = null,
    val returnCode: String? = null,
    val returnMessage: String? = null,
    val atDocCodeID_A: String? = null,
    val returnCode_A: String? = null,
    val returnMessage_A: String? = null,
    val isFilial: Boolean? = null,
    val clienteNome: String? = null,
    val clienteMorada: String? = null,
    val clienteCodigoPostal: String? = null,
    val clienteLocalidade: String? = null,
    val clientePais: String? = null,
    val objRevendedor: EntityAssociated? = null,
    val objGestor: EntityAssociated? = null,
    val _objVendedor: EntityAssociated? = null,
    val objVendedor: EntityAssociated? = null,
    val postPoneQuerys: List<PostPoneQuerys>? = null,
    val prePoneQuerys: List<String>? = null,
    val metodo_entrega: Int? = null
) {
}